let drumMacros = [
    {
       name: "drum 1 patch select",
       CC: 8,
       rangeMin: 0,
       rangeMax: 63,
       default: 0,
    },
    {
       name: "drum 1 level",
       CC: 12,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 1 pitch",
       CC: 14,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 1 decay",
       CC: 15,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 1 distortion",
       CC: 16,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 1 EQ",
       CC: 17,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 1 pan",
       CC: 77,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 2 patch select",
       CC: 18,
       rangeMin: 0,
       rangeMax: 63,
       default: 0,
    },
    {
       name: "drum 2 level",
       CC: 23,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 2 pitch",
       CC: 34,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 2 decay",
       CC: 40,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 2 distortion",
       CC: 42,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 2 EQ",
       CC: 43,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 2 pan",
       CC: 78,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 3 patch select",
       CC: 44,
       rangeMin: 0,
       rangeMax: 63,
       default: 0,
    },
    {
       name: "drum 3 level",
       CC: 45,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 3 pitch",
       CC: 46,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 3 decay",
       CC: 47,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 3 distortion",
       CC: 48,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 3 EQ",
       CC: 49,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 3 pan",
       CC: 79,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 4 patch select",
       CC: 50,
       rangeMin: 0,
       rangeMax: 63,
       default: 0,
    },
    {
       name: "drum 4 level",
       CC: 53,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 4 pitch",
       CC: 55,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 4 decay",
       CC: 57,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 4 distortion",
       CC: 61,
       rangeMin: 0,
       rangeMax: 127,
       default: 0,
    },
    {
       name: "drum 4 EQ",
       CC: 76,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    {
       name: "drum 4 pan",
       CC: 80,
       rangeMin: 0,
       rangeMax: 127,
       default: 64,
    },
    ]